# Generated by Django 5.2.17 on 2026-08-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacaoPluggy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=10)),
                ('contas_atualizadas', models.IntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaldoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('pessoal', 'Pessoal'), ('empresa', 'Empresa')], max_length=10)),
                ('conta_id', models.IntegerField()),
                ('data_referencia', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'unique_together': {('origem', 'conta_id', 'data_referencia')},
            },
        ),
    ]
