# Generated by Django 5.2.17 on 2026-08-15 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('imagem_fundo', models.URLField(blank=True, null=True)),
                ('fonte_escolhida', models.CharField(default='Inter', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_pessoal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaPrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_prevista', models.DateField()),
                ('recebido', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='contas.perfilpessoal')),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('nubank', 'Nubank'), ('bb', 'Banco do Brasil'), ('itau', 'Itaú')], max_length=20)),
                ('pluggy_account_id', models.CharField(max_length=100, unique=True)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='contas.perfilpessoal')),
            ],
            options={
                'unique_together': {('perfil', 'banco')},
            },
        ),
        migrations.CreateModel(
            name='Poupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('valor_guardado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poupancas', to='contas.perfilpessoal')),
            ],
            options={
                'unique_together': {('perfil', 'mes_referencia')},
            },
        ),
    ]
