# Generated by Django 5.2.17 on 2026-08-15 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('prioridade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_conta', models.CharField(choices=[('moradia', 'Moradia'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer e Estilo de Vida'), ('dividas', 'Dívidas e Obrigações')], max_length=20)),
                ('detalhes', models.CharField(blank=True, max_length=200)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='contas.perfilpessoal')),
            ],
            options={
                'ordering': ['prioridade'],
            },
        ),
    ]
