# Generated by Django 5.2.17 on 2026-08-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_contapagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='prioridade',
            field=models.IntegerField(default=0),
        ),
    ]
