# Generated by Django 5.2.17 on 2026-08-15 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razao_social', models.CharField(max_length=150)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('fornecedor', 'Fornecedor'), ('salario', 'Salário'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido')], default='pendente', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='empresas.perfilempresa')),
            ],
            options={
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancariaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('nubank', 'Nubank'), ('bb', 'Banco do Brasil'), ('itau', 'Itaú')], max_length=20)),
                ('pluggy_account_id', models.CharField(max_length=100, unique=True)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='empresas.perfilempresa')),
            ],
            options={
                'unique_together': {('empresa', 'banco')},
            },
        ),
    ]
